services:
  gamecat-db:
    image: mysql:8.4
    container_name: gamecat-banco
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - meus_dados:/var/lib/mysql
      - ./database/gamescat.sql:/docker-entrypoint-initdb.d/gamescat.sql:ro
    
  gamecat-backend:
    build: ./backend
    image: gamecat-back-image
    container_name: gamecat-back-container
    ports:
      - "3000:3000"
    environment:
      HOST: gamecat-db
      USER: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
      DATABASE: ${MYSQL_DATABASE}
})

    depends_on:
      - gamecat-db
  gamecat-frontend:
    build: ./frontend
    image: gamecat-front-image
    container_name: gamecat-front-container 
    ports:
      - "5173:5173"
    depends_on:
      - gamecat-backend


volumes:
  meus_dados: